# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenPrettier < Formula
  desc ""
  homepage "https://github.com/liv7c/homebrew-gen_prettier"
  version "0.5"

  on_macos do
    url "https://github.com/liv7c/gen_prettier/releases/download/v0.5/gen_prettier_Darwin_all.tar.gz"
    sha256 "9844cecd2e150c7fbfe08ef2f5e039a3f210dd0e5c16f93fb7da4d4510aba1d4"

    def install
      bin.install "gen_prettier"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liv7c/gen_prettier/releases/download/v0.5/gen_prettier_Linux_arm64.tar.gz"
      sha256 "bb49459db6e3857ea2845369e19a66c429cf5f8a844a913ce03e322014563bff"

      def install
        bin.install "gen_prettier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/liv7c/gen_prettier/releases/download/v0.5/gen_prettier_Linux_x86_64.tar.gz"
      sha256 "a2e25c69a8397956171a1b6e31b50534079b5dbad78b8dc56519c347c04e08ad"

      def install
        bin.install "gen_prettier"
      end
    end
  end
end
